# Generated by Django 6.0.3 on 2026-04-18 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_keywords', models.TextField(default='', help_text='Comma separated keywords')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_categories', models.ManyToManyField(blank=True, to='articles.category')),
                ('read_articles', models.ManyToManyField(blank=True, related_name='read_by_users', to='articles.article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('read', 'Read'), ('save', 'Save'), ('share', 'Share')], max_length=20)),
                ('interaction_time', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Time spent reading in seconds')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'interaction_time'], name='ai_assistan_user_id_9d1990_idx'), models.Index(fields=['article', 'interaction_type'], name='ai_assistan_article_0ead56_idx')],
                'unique_together': {('user', 'article', 'interaction_type')},
            },
        ),
    ]
