# Generated by Django 6.0.3 on 2026-05-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('chennai', 'Chennai'), ('kolkata', 'Kolkata'), ('pune', 'Pune'), ('jaipur', 'Jaipur'), ('lucknow', 'Lucknow'), ('kanpur', 'Kanpur'), ('ahmedabad', 'Ahmedabad'), ('surat', 'Surat'), ('vadodara', 'Vadodara'), ('indore', 'Indore'), ('nagpur', 'Nagpur'), ('bhopal', 'Bhopal'), ('cochin', 'Cochin'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('coimbatore', 'Coimbatore'), ('vizag', 'Vizag'), ('vijayawada', 'Vijayawada'), ('patna', 'Patna'), ('guwahati', 'Guwahati'), ('chandigarh', 'Chandigarh'), ('shimla', 'Shimla')], default='mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal')], default='maharashtra', max_length=50),
        ),
    ]
